### PR TITLE
Fix for no devices returned when starting scan on android.

### PR DESCRIPTION
**Pull request by ziakhan110**
This PR fixes the following issue:
Empty devices returned when starting scan on android 12+, on app resetart after permissions were given, startScan would return devices.

The issue:
There is error in android java code , when first time startScan is called, the library asks for permission.
On permission result the code would crash and no result would return to flutter side.

The fix:
Fix the permission asking flow and correctly return result to flutter code from native code.

Refactoring:
Fixed some boolean conditions checks.
Code reformat

### CODE REVIEW

**Comment by Maqcel** [comment]
Hi thanks for this issue I'm also affected by this, when app is first launching and after calling for the permissions and starting scanning for the devices I'm stuck Logs bellow:
```
D/[FBP-Android]( 4257): [FBP] onMethodCall: flutterRestart
D/[FBP-Android]( 4257): [FBP] initializing BluetoothAdapter
D/CompatibilityChangeReporter( 4257): Compat change id reported: 263076149; UID 10504; state: ENABLED
I/BluetoothAdapter( 4257): BluetoothAdapter() : _APPNAME_
D/BluetoothAdapter( 4257): getBleEnabledArray(): ON
I/BluetoothAdapter( 4257): BLE support array set: [true, true, true, true, true, true, true]
D/[FBP-Android]( 4257): [FBP] disconnectAllDevices(flutterRestart)
D/[FBP-Android]( 4257): [FBP] connectedPeripherals: 0
D/[FBP-Android]( 4257): [FBP] onMethodCall: getAdapterState
[log] onChange(OnboardingCubit, Change { currentState: OnboardingState.stepBluetooth(), nextState: OnboardingState.stepLocalization() })
I/ImeFocusController( 4257): onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
I/ImeFocusController( 4257): onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
D/InputTransport( 4257): Input channel destroyed: 'ClientS', fd=135
D/CompatibilityChangeReporter( 4257): Compat change id reported: 78294732; UID 10504; state: ENABLED
I/InsetsSourceConsumer( 4257): applyRequestedVisibilityToControl: visible=true, type=statusBars, host=_APPNAME_.MainActivity
I/InsetsSourceConsumer( 4257): applyRequestedVisibilityToControl: visible=true, type=navigationBars, host=_APPNAME_.MainActivity
I/flutter ( 4257): [FBP] [1;30m<setLogLevel>[0m args: [1;35m5[0m
D/[FBP-Android]( 4257): [FBP] onMethodCall: setLogLevel
I/flutter ( 4257): [FBP] [1;30m<setLogLevel>[0m result: [1;33mtrue[0m
[log] onChange(OnboardingCubit, Change { currentState: OnboardingState.stepLocalization(), nextState: OnboardingState.stepPair() })
D/InputMethodManagerUtils( 4257): startInputInner - Id : 0
I/InputMethodManager( 4257): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
I/InsetsSourceConsumer( 4257): applyRequestedVisibilityToControl: visible=false, type=ime, host=_APPNAME_
I/flutter ( 4257): [FBP] [1;30m<startScan>[0m args: [1;35m{with_services: [1809], with_remote_ids: [], with_names: [DeviceName], with_keywords: [], with_msd: [], with_service_data: [], continuous_updates: false, continuous_divisor: 1, android_legacy: false, android_scan_mode: 2, android_uses_fine_location: false}[0m
D/[FBP-Android]( 4257): [FBP] onMethodCall: startScan
```

After Hot restart/relaunching the app the resulting logs are bellow:
```
D/[FBP-Android]( 9712): [FBP] onMethodCall: flutterRestart
D/[FBP-Android]( 9712): [FBP] initializing BluetoothAdapter
D/CompatibilityChangeReporter( 9712): Compat change id reported: 263076149; UID 10505; state: ENABLED
I/BluetoothAdapter( 9712): BluetoothAdapter() : _APPNAME_
D/BluetoothAdapter( 9712): getBleEnabledArray(): ON
I/BluetoothAdapter( 9712): BLE support array set: [true, true, true, true, true, true, true]
D/[FBP-Android]( 9712): [FBP] disconnectAllDevices(flutterRestart)
D/[FBP-Android]( 9712): [FBP] connectedPeripherals: 0
D/[FBP-Android]( 9712): [FBP] onMethodCall: getAdapterState
[log] onChange(OnboardingCubit, Change { currentState: OnboardingState.stepBluetooth(), nextState: OnboardingState.stepLocalization() })
D/ProfileInstaller( 9712): Installing profile for _APPNAME_
I/flutter ( 9712): [FBP] [1;30m<setLogLevel>[0m args: [1;35m5[0m
D/[FBP-Android]( 9712): [FBP] onMethodCall: setLogLevel
I/flutter ( 9712): [FBP] [1;30m<setLogLevel>[0m result: [1;33mtrue[0m
[log] onChange(OnboardingCubit, Change { currentState: OnboardingState.stepLocalization(), nextState: OnboardingState.stepPair() })
I/flutter ( 9712): [FBP] [1;30m<startScan>[0m args: [1;35m{with_services: [1809], with_remote_ids: [], with_names: [DeviceName], with_keywords: [], with_msd: [], with_service_data: [], continuous_updates: false, continuous_divisor: 1, android_legacy: false, android_scan_mode: 2, android_uses_fine_location: false}[0m
D/[FBP-Android]( 9712): [FBP] onMethodCall: startScan
(2) D/BluetoothAdapter( 9712): getBleEnabledArray(): ON
D/BluetoothAdapter( 9712): semIsBleEnabled(): ON
D/BluetoothAdapter( 9712): getBleEnabledArray(): ON
D/BluetoothLeScanner( 9712): Start Scan with callback
D/BluetoothLeScanner( 9712): onScannerRegistered() - status=0 scannerId=9 mScannerId=0
I/flutter ( 9712): [FBP] [1;30m<startScan>[0m result: [1;33mtrue[0m
D/[FBP-Android]( 9712): [FBP] onScanResult
I/BluetoothAdapter( 9712): BluetoothAdapter() : _APPNAME_
I/flutter ( 9712): [FBP] [1;30m[[ OnScanResponse ]][0m result: [1;33m{advertisements: [...]}[0m
D/[FBP-Android]( 9712): [FBP] onScanResult
I/flutter ( 9712): [FBP] [1;30m[[ OnScanResponse ]][0m result: [1;33m{advertisements: [...]}[0m
```

After running your fork the problem no longer exists, but I wanted to add 12 warnings I'm getting on compilation:
```
Launching lib/main.dart on SM S901B in debug mode...
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:439: warning: [deprecation] disable() in BluetoothAdapter has been deprecated[0m
                        boolean disabled = mBluetoothAdapter.disable();
                                                            ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:906: warning: [deprecation] setValue(byte[]) in BluetoothGattCharacteristic has been deprecated[0m
                        if (!characteristic.setValue(hexToBytes(value))) {
                                           ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:915: warning: [deprecation] writeCharacteristic(BluetoothGattCharacteristic) in BluetoothGatt has been deprecated[0m
                        if (!gatt.writeCharacteristic(characteristic)) {
                                 ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1034: warning: [deprecation] setValue(byte[]) in BluetoothGattDescriptor has been deprecated[0m
                        if (!descriptor.setValue(hexToBytes(value))) {
                                       ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1040: warning: [deprecation] writeDescriptor(BluetoothGattDescriptor) in BluetoothGatt has been deprecated[0m
                        if (!gatt.writeDescriptor(descriptor)) {
                                 ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1151: warning: [deprecation] setValue(byte[]) in BluetoothGattDescriptor has been deprecated[0m
                        if (!cccd.setValue(descriptorValue)) {
                                 ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1157: warning: [deprecation] writeDescriptor(BluetoothGattDescriptor) in BluetoothGatt has been deprecated[0m
                        if (!gatt.writeDescriptor(cccd)) {
                                 ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1892: warning: [deprecation] <T>getParcelableExtra(String) in Intent has been deprecated[0m
                device = intent.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);
                               ^
  where T is a type-variable:
    T extends Parcelable declared in method <T>getParcelableExtra(String)
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:2390: warning: [deprecation] onCharacteristicRead(BluetoothGatt,BluetoothGattCharacteristic,int) in BluetoothGattCallback has been deprecated[0m
        public void onCharacteristicRead(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status) {
                    ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:2394: warning: [deprecation] getValue() in BluetoothGattCharacteristic has been deprecated[0m
            this.onCharacteristicRead(gatt, characteristic, characteristic.getValue(), status);
                                                                          ^
[2m/Users/maqcel/.pub-cache/git/flutter_blue_plus-a3c7666c9f57e4e71642b37478c6f2613c13608d/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:2399: warning: [deprecation] onDescriptorRead(BluetoothGatt,BluetoothGattDescriptor,int) in BluetoothGattCallback has been deprecated[0m
        public void onDescriptorRead(BluetoothGatt gatt, BluetoothGattDescriptor descriptor, int status) {
                    ^
```

**Comment by chipweinberger** [comment]
please do a **minimal** PR and fix all the warnings.

Don't reformat the code, it makes it really hard to see what you changed.

**Comment by chipweinberger** [comment]
this problem started in 1.32.12: https://github.com/chipweinberger/flutter_blue_plus/pull/975

**Comment by ziakhan110** [comment]
I am preparing minimal fix, it will make it clear.

**Comment by chipweinberger** [comment]
I pushed this to master: bd9074a307ea7b68a5d629b1e730c9a006bff76c

please let me know if it fixes the problem. I just used ChatGPT for it.

**Comment by chipweinberger** [comment]
> On permission result the code would crash and no result would return to flutter side.

What is the stacktrace?

**Comment by ziakhan110** [comment]
I did not see crash, but it did not return results, so i assumed it crashed somewhere.

**Comment by ziakhan110** [comment]
I have removed most of the formmatting , android studio adds tabs changes.

**Comment by chipweinberger** [comment]
try 1.33.3

**Comment by ziakhan110** [comment]
Why not accept my PR?

**Comment by chipweinberger** [comment]
too many changes

**Comment by ziakhan110** [comment]
How can i avoid these, Are you using some special formatting styles?

**Comment by chipweinberger** [comment]
I use VSC without automatic formatting.

Also:
* you accidentally deleted some strings in `gattErrorString`
* you changed `void op(boolean granted, String permission);` but no good reason to change it

Thank you for finding this issue and fixing it.

Please try 1.33.3 and tell me if it works for you.

**Comment by ziakhan110** [comment]
It already works for me, i have migrated to Kotlin.

**Comment by chipweinberger** [comment]
> void op(boolean granted, String permission); is always called with null

good point. this was a recent regression in 1.32.13

**Pull request closed without merging**
