### PR TITLE
fixs "Android: SCAN_FAILED_ALREADY_STARTED after turning Bluetooth Off then On #849update :

### PR DESCRIPTION
**Pull request by tucici**
fixs "Android: SCAN_FAILED_ALREADY_STARTED after turning Bluetooth Off then On #849

### CODE REVIEW

**Comment by chipweinberger** [comment]
we already have this code. why is this code not sufficient?

```
    // keep track of adapter states
    if (call.method == "OnAdapterStateChanged") {
      BmBluetoothAdapterState r = BmBluetoothAdapterState.fromMap(call.arguments);
      _adapterStateNow = r.adapterState;
      if (isScanningNow && r.adapterState != BmAdapterStateEnum.on) {
        _stopScan(invokePlatform: false);
      }
```

can you share your logs of the problem happening.

also, why set it to null? why not just call "stopScan"?

**Comment by tucici** [comment]
> please share logs of the problem
> 
> we already have this code. why is this code not sufficient? race condition?
> 
> ```
>     // keep track of adapter states
>     if (call.method == "OnAdapterStateChanged") {
>       BmBluetoothAdapterState r = BmBluetoothAdapterState.fromMap(call.arguments);
>       _adapterStateNow = r.adapterState;
>       if (isScanningNow && r.adapterState != BmAdapterStateEnum.on) {
>         _stopScan(invokePlatform: false);
>       }
> ```
> 
> also, why set it to null? why not just call "stopScan"?

I've submitted a new issue，[look here](https://github.com/chipweinberger/flutter_blue_plus/issues/1002)

**Comment by chipweinberger** [comment]
this was our previous fix

https://github.com/chipweinberger/flutter_blue_plus/commit/99740a73c221c9d79837fe2be804962583e3dcfd

**Comment by chipweinberger** [comment]
thanks for submitting. 

can your new code go in this existing section?

```
            // stop scanning when adapter is turned off. 
            // Otherwise, scanning automatically resumes when the adapter is
            // turned back on. I don't think most users expect that.
            if (adapterState != BluetoothAdapter.STATE_ON) {
                if (mBluetoothAdapter != null && mIsScanning) {
                    BluetoothLeScanner scanner = mBluetoothAdapter.getBluetoothLeScanner();
                    if (scanner != null) {
                        scanner.stopScan(getScanCallback());
                        mIsScanning = false;
                    }
                }
            }
```

**Comment by chipweinberger** [comment]
I'm not sure if `scanCallback = null` actually stops the scan. so your phone might still be scanning and wasting power when BLE is re-enabled.

**Comment by tucici** [comment]
> I'm not sure if `scanCallback = null` actually stops the scan. so your phone might still be scanning and wasting power when BLE is re-enabled.
> 
> Ideally we should fix `stopScan` so that it actually stops the scan.


` private final Map<ScanCallback, BleScanCallbackWrapper> mLeScanClients;`

`  @RequiresLegacyBluetoothAdminPermission
    @RequiresBluetoothScanPermission
    @RequiresPermission(android.Manifest.permission.BLUETOOTH_SCAN)
    public void stopScan(ScanCallback callback) {
        BluetoothLeUtils.checkAdapterStateOn(mBluetoothAdapter);
        synchronized (mLeScanClients) {
            BleScanCallbackWrapper wrapper = mLeScanClients.remove(callback);
            if (wrapper == null) {
                if (DBG) Log.d(TAG, "could not find callback wrapper");
                return;
            }
            wrapper.stopLeScan();
        }
    }`

`   @RequiresPermission(android.Manifest.permission.BLUETOOTH_SCAN)
    private int startScan(List<ScanFilter> filters, ScanSettings settings,
            final WorkSource workSource, final ScanCallback callback,
            final PendingIntent callbackIntent) {
        BluetoothLeUtils.checkAdapterStateOn(mBluetoothAdapter);
        if (callback == null && callbackIntent == null) {
            throw new IllegalArgumentException("callback is null");
        }
        if (settings == null) {
            throw new IllegalArgumentException("settings is null");
        }
        synchronized (mLeScanClients) {
            if (callback != null && mLeScanClients.containsKey(callback)) {
                return postCallbackErrorOrReturn(callback,
                            ScanCallback.SCAN_FAILED_ALREADY_STARTED);
            }
            IBluetoothGatt gatt;
            try {
                gatt = mBluetoothManager.getBluetoothGatt();
            } catch (RemoteException e) {
                gatt = null;
            }
            if (gatt == null) {
                return postCallbackErrorOrReturn(callback, ScanCallback.SCAN_FAILED_INTERNAL_ERROR);
            }
            if (!isSettingsConfigAllowedForScan(settings)) {
                return postCallbackErrorOrReturn(callback,
                        ScanCallback.SCAN_FAILED_FEATURE_UNSUPPORTED);
            }
            if (!isHardwareResourcesAvailableForScan(settings)) {
                return postCallbackErrorOrReturn(callback,
                        ScanCallback.SCAN_FAILED_OUT_OF_HARDWARE_RESOURCES);
            }
            if (!isSettingsAndFilterComboAllowed(settings, filters)) {
                return postCallbackErrorOrReturn(callback,
                        ScanCallback.SCAN_FAILED_FEATURE_UNSUPPORTED);
            }
            if (callback != null) {
                BleScanCallbackWrapper wrapper = new BleScanCallbackWrapper(gatt, filters,
                        settings, workSource, callback);
                wrapper.startRegistration();
            } else {
                try {
                    final SynchronousResultReceiver recv = SynchronousResultReceiver.get();
                    gatt.startScanForIntent(callbackIntent, settings, filters,
                            mAttributionSource, recv);
                    recv.awaitResultNoInterrupt(getSyncTimeout()).getValue(null);
                } catch (TimeoutException | RemoteException e) {
                    return ScanCallback.SCAN_FAILED_INTERNAL_ERROR;
                }
            }
        }
        return ScanCallback.NO_ERROR;
    }
`




I can't see the code implementation in "BluetoothLeUtils.checkAdapterStateOn(mBluetoothAdapter)". 

My guess is that when Bluetooth is turned off, FBP calls stopScan, and since the Bluetooth adapter is off, there may be an exception thrown inside, preventing the implementation of subsequent code, resulting in the Map"(mLeScanClients)" not being cleared correctly.  


Whatever, resetting scanCallback in FBP when the bluetooth adapter is turned off, it`s does work for me

**Comment by chipweinberger** [comment]
perhaps when BLE is reenabled, we should check `mIsScanning` and call `stopScan` if scanning is supposed to be off

**Comment by chipweinberger** [comment]
please verify this code is called

```
            // stop scanning when adapter is turned off. 
            // Otherwise, scanning automatically resumes when the adapter is
            // turned back on. I don't think most users expect that.
            if (adapterState != BluetoothAdapter.STATE_ON) {
                if (mBluetoothAdapter != null && mIsScanning) {
                    BluetoothLeScanner scanner = mBluetoothAdapter.getBluetoothLeScanner();
                    if (scanner != null) {
                        /// please add a log here
                        scanner.stopScan(getScanCallback());
                        mIsScanning = false;
                    }
                }
                scanCallback = null; // add it here
            }
```

**Comment by tucici** [comment]
> please verify this code is called

yes, it`s works too

**Comment by chipweinberger** [comment]
> perhaps when BLE is reenabled, we should check `mIsScanning` and call `stopScan` if needed
> 
> `scanCallback = null` will not actually stop the scan, afaict. But yes its an easy solution to fix the error.

please try this

**Comment by chipweinberger** [comment]
do you need this fixed anymore?

**Comment by chipweinberger** [comment]
I just tried your steps, in the Example app

1. press scan
2. turn off bluetooth before scan finished
3. turn on bluetooth
4. press scan

I did not have problems

**Comment by chipweinberger** [comment]
Even though I did not have a problem, I noticed this code was not doing anything because `scanner` is null.

```
            // stop scanning when bluetooth is turned off
            if (adapterState != BluetoothAdapter.STATE_ON) {
                if (mBluetoothAdapter != null && mIsScanning) {
                    BluetoothLeScanner scanner = mBluetoothAdapter.getBluetoothLeScanner();
                    if (scanner != null) {
                        scanner.stopScan(getScanCallback());
                        mIsScanning = false;
                    }
                }
            }
```

therefore I changed it to this:

```
            // stop scanning when bluetooth is turned back on
            if (adapterState != BluetoothAdapter.STATE_ON) {
                if (mBluetoothAdapter != null && mIsScanning) {
                    BluetoothLeScanner scanner = mBluetoothAdapter.getBluetoothLeScanner();
                    if (scanner != null) {
                        scanner.stopScan(getScanCallback());
                        mIsScanning = false;
                    }
                }
            }
```

let me know if you have problems

**Pull request closed without merging**
