### PR TITLE
[Feature]: Handle time out in startScan Method

### PR DESCRIPTION
**Pull request by OmarAly92**
This pull request introduces an optional onTimeout parameter to the startScan method. The onTimeout callback function is triggered in the stopScan method when the scan times out, providing user a way to handle timeout events directly.

**Changes**

- Added void Function()? onTimeout as an optional parameter to startScan.
- Updated _scanTimeout in stopScan to invoke onTimeout?.call() after the scan stops due to a timeout.

**Benefit**

This improvement allows developers to handle timeout events with a custom callback, increasing flexibility and control over scan behavior.

**Testing**

I have tested the changes, and the functionality is working as expected. The onTimeout callback is triggered correctly upon timeout.

### CODE REVIEW

**Comment by chipweinberger** [comment]
pretty good idea. 

currently you would use `isScanning` to do this

**Comment by OmarAly92** [comment]
Making timeout manual is a good approach and working well but adding it inside package makes it easier for users to handle timeouts without extra setup

**Comment by chipweinberger** [comment]
there is a problem

```
            await stopScan();
            onTimeout?.call();
```

if `stopScan` throws exception, then `onTimeout` will not be called.

**Comment by chipweinberger** [comment]
also another problem: if the user calls `stopScan` manually, the `onTimeout` will not be called.

**Comment by chipweinberger** [comment]
i will not merge this. I suggest you use `FlutterBluePlus.isScanning` to detect when scanning stops.

**Pull request closed without merging**
